CREATE TABLE online_retail (
    InvoiceNo TEXT,
    StockCode TEXT,
    Description TEXT,
    Quantity INT,
    InvoiceDate TIMESTAMP,
    UnitPrice NUMERIC,
    CustomerID TEXT,
    Country TEXT
);

copy online_retail
FROM 'D:\Downloads\sql_dataset\OnlineRetail.csv'
DELIMITER ','
CSV HEADE
ENCODING 'LATIN1';


-- Total records in dataset

SELECT
	COUNT(*) FROM online_retail;


-- Total unique customers

SELECT
	COUNT(DISTINCT customerid) 
FROM online_retail;


-- Dataset date range

SELECT
	MIN(invoicedate), MAX(invoicedate)
FROM ONLINE_RETAIL;


-- Identify invalid / cancelled / null customer transactions

SELECT * 
FROM online_retail
WHERE quantity <= 0
	OR invoiceno LIKE 'C%'
	OR customerid IS NULL;


-- DATA CLEANING

CREATE TABLE clean_retail AS 
SELECT * 
FROM online_retail
WHERE quantity > 0
	AND invoiceno NOT LIKE 'C%'
	AND customerid IS NOT NULL;


-- Row count after cleaning

SELECT 
	COUNT(*) FROM clean_retail;


-- Revenue generated by each customer

SELECT 
	customerid,
	SUM(quantity * unitprice) AS 
	revenue
FROM clean_retail
GROUP BY customerid;


-- Total orders per customer (Frequency)

SELECT 
	customerid,
	COUNT(DISTINCT invoiceno) AS 
	total_orders
FROM clean_retail
GROUP BY customerid;


-- Most recent purchase date per customer

SELECT 
	customerid,
	MAX(invoicedate) AS 
	last_order_date
FROM clean_retail
GROUP BY customerid;


-- Recency calculation in days

SELECT 
	customerid,
	CURRENT_DATE - MAX(invoicedate :: DATE) AS
	recency_days
FROM clean_retail
GROUP BY customerid;


-- RFM CUSTOMER SEGMENTATION

CREATE TABLE final_segment AS


--Base RFM metrics calculation
	
WITH base AS(
SELECT 
	customerid,
	COUNT(DISTINCT invoiceno) AS 
	frequency,
	SUM(quantity * unitprice) AS 
	monetary,
	CURRENT_DATE - MAX(invoicedate :: DATE) AS
	recency_days
FROM clean_retail
GROUP BY customerid),



-- RFM scoring using NTILE window functions

rfm AS (SELECT 
	customerid,
	recency_days,
	frequency,
	monetary,
	
	NTILE(5) OVER(ORDER  BY recency_days DESC) AS 
	r_score,
	NTILE(5) OVER(ORDER  BY frequency) AS
	f_score,
	NTILE(5) OVER(ORDER  BY monetary) AS
	m_score

FROM base),


-- Customer segmentation using CASE WHEN logic
	
segments AS(SELECT *,
	CASE 
WHEN r_score <= 2 AND f_score = 1 THEN 'lost'
WHEN r_score <= 2 AND f_score >= 2 THEN 'at risk repeat'
WHEN r_score >= 3 AND f_score = 1 THEN 'new'
WHEN r_score >= 3 AND f_score >= 2 THEN 'active repeat'
ELSE 'others'
END AS segment
FROM rfm)
SELECT *
FROM segments;
	

-- Final segmented customer table

SELECT
	r_score,
	f_score,
	m_score,
	COUNT(*)
FROM final_segment
WHERE segment = 'others'
GROUP BY r_score, f_score, m_score
ORDER BY COUNT(*) DESC;


--Customer count by segment

SELECT 
	segment, COUNT(*) 
FROM final_segment
GROUP BY segment
ORDER BY COUNT(*) DESC;


--Revenue contribution by customer segment

SELECT 
	segment,
	SUM(monetary) AS 
	total_revenue
FROM final_segment
GROUP BY segment
ORDER BY total_revenue DESC;


--Revenue comparison between customer segment

SELECT 
	segment,
	SUM(monetary) AS revenue
FROM final_segment
GROUP BY segment
ORDER BY revenue;


-- One time vs repeat customer analysis

SELECT 
	CASE WHEN frequency = 1
THEN 'one_time'
	ELSE 'repeat_customer'
	END AS type,
	COUNT(*)
FROM final_segment
GROUP BY 	CASE WHEN frequency = 1
THEN 'one_time'
	ELSE 'repeat_customer'
	END;


--Segment-wise customer count, revenue, and average spend analysis
SELECT 
	segment,
	COUNT(*) AS customers,
	SUM(monetary) AS revenue,
	ROUND(AVG(monetary), 2) AS 
	av_spend
FROM final_segment
GROUP BY segment
ORDER BY revenue DESC;


--Top 10 highest spending customers
SELECT *
FROM final_segment
ORDER BY monetary DESC
LIMIT 10;


